// apps/vue_app/src/App.vue
<script setup lang="ts">
import type { ApiHealthResponse, ApiListResponse, Todo, User } from '@repo/shared';
import { computed, onMounted, ref } from 'vue';

const apiBase = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';

const todos = ref<Todo[]>([]);
const title = ref('');
const snapshot = ref('Loading…');

async function fetchJson<T>(input: string, init?: RequestInit): Promise<T> {
  const res = await fetch(input, init);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()) as T;
}

async function loadTodos() {
  const res = await fetchJson<ApiListResponse<Todo>>(`${apiBase}/todos`);
  todos.value = res.data ?? [];
}

onMounted(async () => {
  try {
    const [health, users] = await Promise.all([
      fetchJson<ApiHealthResponse>(`${apiBase}/health`),
      fetchJson<ApiListResponse<User>>(`${apiBase}/users`),
    ]);
    snapshot.value = JSON.stringify({ health, users }, null, 2);
    await loadTodos();
  } catch (e) {
    snapshot.value = `API error: ${String(e)}`;
  }
});

const count = computed(() => todos.value.length);

async function addTodo() {
  const t = title.value.trim();
  if (!t) return;
  await fetch(`${apiBase}/todos`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title: t }),
  });
  title.value = '';
  await loadTodos();
}

async function toggle(todo: Todo, completed: boolean) {
  const updated = await fetchJson<Todo>(`${apiBase}/todos/${todo.id}`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ completed }),
  });
  todos.value = todos.value.map((x) => (x.id === updated.id ? updated : x));
}
</script>

<template>
  <div class="repo-app">
    <div class="repo-container">
      <header class="repo-card">
        <h1 class="repo-title">Vue 3 + Vite</h1>
        <p class="repo-subtitle">
          Composition API · API: <code>{{ apiBase }}</code>
        </p>
        <div class="repo-row">
          <input
            v-model="title"
            class="repo-input"
            placeholder="Add todo"
            @keydown.enter="addTodo"
          />
          <button class="repo-btn repo-btn--primary" type="button" @click="addTodo">Add</button>
        </div>
        <p class="repo-badge">Count: {{ count }}</p>
        <ul class="repo-list">
          <li v-for="todo in todos" :key="todo.id" class="repo-item">
            <input
              type="checkbox"
              :checked="todo.completed"
              @change="toggle(todo, ($event.target as HTMLInputElement).checked)"
            />
            <span :style="{ textDecoration: todo.completed ? 'line-through' : undefined }">{{
              todo.title
            }}</span>
          </li>
        </ul>
        <pre class="repo-kv">{{ snapshot }}</pre>
      </header>
    </div>
  </div>
</template>

// apps/react_app/src/App.tsx
import type { ApiHealthResponse, ApiListResponse, Todo, User } from '@repo/shared';
import { useCallback, useEffect, useMemo, useState } from 'react';

const apiBase = import.meta.env.VITE_API_URL ?? 'http://localhost:3000';

async function fetchJson<T>(input: string, init?: RequestInit): Promise<T> {
  const res = await fetch(input, init);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return (await res.json()) as T;
}

export default function App() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [title, setTitle] = useState('');
  const [snapshot, setSnapshot] = useState<string>('Loading…');

  const load = useCallback(async () => {
    const res = await fetchJson<ApiListResponse<Todo>>(`${apiBase}/todos`);
    setTodos(res.data ?? []);
  }, []);

  useEffect(() => {
    void (async () => {
      try {
        const [health, users] = await Promise.all([
          fetchJson<ApiHealthResponse>(`${apiBase}/health`),
          fetchJson<ApiListResponse<User>>(`${apiBase}/users`),
        ]);
        setSnapshot(JSON.stringify({ health, users }, null, 2));
        await load();
      } catch (e) {
        setSnapshot(`API error: ${String(e)}`);
      }
    })();
  }, [load]);

  const count = useMemo(() => todos.length, [todos]);

  async function addTodo() {
    const t = title.trim();
    if (!t) return;
    await fetch(`${apiBase}/todos`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: t }),
    });
    setTitle('');
    await load();
  }

  async function toggle(id: string, completed: boolean) {
    const updated = await fetchJson<Todo>(`${apiBase}/todos/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ completed }),
    });
    setTodos((prev) => prev.map((x) => (x.id === id ? updated : x)));
  }

  return (
    <div className="repo-app">
      <div className="repo-container">
        <header className="repo-card">
          <h1 className="repo-title">React + Vite</h1>
          <p className="repo-subtitle">
            Hooks + fetch · API: <code>{apiBase}</code>
          </p>
          <div className="repo-row">
            <input
              className="repo-input"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Add todo"
              onKeyDown={(e) => e.key === 'Enter' && void addTodo()}
            />
            <button className="repo-btn repo-btn--primary" type="button" onClick={() => void addTodo()}>
              Add
            </button>
          </div>
          <p className="repo-badge">Count: {count}</p>
          <ul className="repo-list">
            {todos.map((todo) => (
              <li key={todo.id} className="repo-item">
                <input
                  type="checkbox"
                  checked={todo.completed}
                  onChange={(e) => void toggle(todo.id, e.target.checked)}
                />
                <span style={{ textDecoration: todo.completed ? 'line-through' : undefined }}>{todo.title}</span>
              </li>
            ))}
          </ul>
          <pre className="repo-kv">{snapshot}</pre>
        </header>
      </div>
    </div>
  );
}
